[workspace]
members = ["app", "bootstrap", "shared", "frontend", "axum_backend"]
resolver = "2"

[workspace.package]
license = "MIT"
license-file = "LICENSE"
authors = ["Pascal Behmenburg"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
