[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Z", "threads=8", "-C", "link-arg=-fuse-ld=/usr/bin/mold"]

[target.aarch64-apple-darwin]
linker = "clang"
rustflags = ["-Z", "threads=8", "-C", "link-arg=-fuse-ld=/usr/local/bin/ld64.sold"]

[target.x86_64-apple-darwin]
linker = "clang"
rustflags = ["-Z", "threads=8", "-C", "link-arg=-fuse-ld=/usr/local/bin/ld64.sold"]