# this file is used for testing the api using the REST Client extension in VS Code
# it may also provide infos for tools
@host = http://localhost:8000/api
@todo_id = 3

### create todo
POST {{host}}/v1/todos HTTP/1.1
Content-Type: application/json

{
    "title": "Task title",
    "description": "Task description"
}

### update todo
PUT {{host}}/v1/todos HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "title": "Updated task title",
    "description": "Updated task description",
    "is_done": true
}

### get all todos
GET {{host}}/v1/todos HTTP/1.1

### get todo
GET {{host}}/v1/todos/{{todo_id}} HTTP/1.1

### get bad todo
GET {{host}}/v1/todos/4000 HTTP/1.1


### delete todo
DELETE {{host}}/v1/todos/{{todo_id}} HTTP/1.1